services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: ytclipper-backend-dev
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app
    networks:
      - ytclipper-dev-network

networks:
  ytclipper-dev-network:
    driver: bridge
