version: '3.8'

services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: ytclipper-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - ytclipper-dev-network

  # Backend API (Development mode)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: ytclipper-backend-dev
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - '8080:8080'
    volumes:
      - ../backend:/app
    depends_on:
      - redis
    networks:
      - ytclipper-dev-network

networks:
  ytclipper-dev-network:
    driver: bridge
