services:
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/priyabratamo/ytclipper/backend:latest}
    container_name: ytclipper-${CONTAINER_SUFFIX:-default}-backend
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - ENV=${ENV:-staging}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_PRETTY=${LOG_PRETTY:-true}
      - API_TIMEOUT=${API_TIMEOUT:-30s}
      - GIN_MODE=${GIN_MODE:-release}
      - PORT=${BACKEND_PORT:-8080}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_PORT:-8080}/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  app:
    image: ${FRONTEND_IMAGE:-ghcr.io/priyabratamo/ytclipper/frontend:latest}
    container_name: ytclipper-${CONTAINER_SUFFIX:-default}-app
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT:-3000}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:${FRONTEND_PORT:-3000}/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

# Explicitly disable default network creation
networks:
  default:
    external: true
    name: bridge
