name: Cleanup

on:
  schedule:
    - cron: "0 2 * * 0" # Weekly at 2 AM on Sunday
  workflow_dispatch:
    inputs:
      cleanup_type:
        description: "Type of cleanup"
        required: true
        default: "images"
        type: choice
        options:
          - images
          - containers
          - volumes
          - all

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Cleanup Docker resources
        run: |
          CLEANUP_TYPE="${{ github.event.inputs.cleanup_type || 'images' }}"

          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            echo 'Starting cleanup: ${CLEANUP_TYPE}'
            
            case ${CLEANUP_TYPE} in
              'images')
                docker image prune -af
                ;;
              'containers')
                docker container prune -f
                ;;
              'volumes')
                docker volume prune -f
                ;;
              'all')
                docker system prune -af --volumes
                ;;
            esac
            
            echo 'Cleanup completed'
            docker system df
          "
