name: Health Check

on:
  schedule:
    - cron: "*/15 * * * *" # Every 15 minutes
  workflow_dispatch:

jobs:
  health-check:
    name: 🔍 Health Check (Production)
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 🚑 Run Health Check Script on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail

            echo "🩺 Starting health checks for ytclipper production"

            COMPOSE_DIR="/opt/ytclipper"
            COMPOSE_FILE="$COMPOSE_DIR/compose.yml"

            # 1. Check running containers
            echo "📦 Checking running containers..."
            docker compose -f "$COMPOSE_FILE" ps

            # 2. Backend health check
            echo "🔁 Checking backend health at http://localhost:8080/health"
            if curl --fail --silent --max-time 5 http://localhost:8080/health; then
              echo "✅ Backend is healthy"
            else
              echo "❌ Backend health check failed"
              exit 1
            fi

            # 3. Frontend health check
            echo "🌐 Checking frontend health at http://localhost:3000/"
            if curl --fail --silent --max-time 5 http://localhost:3000/; then
              echo "✅ Frontend is healthy"
            else
              echo "❌ Frontend health check failed"
              exit 1
            fi

            # 4. Postgres health check
            echo "🐘 Checking Postgres container with pg_isready"
            if docker compose -f "$COMPOSE_FILE" exec -T postgres pg_isready; then
              echo "✅ Database is healthy"
            else
              echo "❌ Database health check failed"
              exit 1
            fi

            echo "🏁 All checks passed!"

      - name: ✅ Health Check Summary
        if: success()
        run: |
          echo "## ✅ All Services Healthy" >> $GITHUB_STEP_SUMMARY
          echo "- Backend: 🟢 Healthy" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend: 🟢 Healthy" >> $GITHUB_STEP_SUMMARY
          echo "- Database: 🟢 Healthy" >> $GITHUB_STEP_SUMMARY

      - name: ❌ Alert on Failure
        if: failure()
        run: |
          echo "## ❌ Health Check Failed" >> $GITHUB_STEP_SUMMARY
          echo "- One or more services are **unhealthy**." >> $GITHUB_STEP_SUMMARY
          echo "- Check VPS logs via SSH or Docker logs." >> $GITHUB_STEP_SUMMARY
